# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f038745e5bae1a7bc8464dd9e293d66e0403d5d3368c27124da4803d6e7e95750ed071cd7d6bf676388a8f422fc8f767d6ee8d9b285afed089b92e39f8b14731

test:
  secret_key_base: 4edeb9a38903baf44664c540c1c7186bd50648a6b6f5b6d52e6c4db46a33f8255688bbf6d3deabe5e281fcec53ee23c3929bd1fc956126b07e6fa3a5d117067e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
